[uwsgi]
# application's base folder
base = /home/danny/perks
pythonpath = %(base)

# python module to import
module = perks:app

# socket file's location
socket = /var/uwsgi/perks.sock

# permissions for the socket file
chmod-socket = 666

# the variable that holds a flask application
callable = app

# location of log files
logto = /var/log/%n.log

# processes = 4
# threads = 2
idle = 600
die-on-idle = True
manage-script-name = True
wsgi-file = %(base)/wsgi.py
master = True
cheap = True
