"""add more fields

Revision ID: 243a24126f8a
Revises: 28763d0d098a
Create Date: 2017-08-09 22:46:49.064029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243a24126f8a'
down_revision = '28763d0d098a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_401k_plan', sa.Column('employer_max_contribution', sa.Numeric(precision=9, scale=2), nullable=False))
    op.add_column('employee_401k_plan', sa.Column('employer_percent_matched', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('employee_401k_plan', sa.Column('min_contribution', sa.Numeric(precision=9, scale=2), nullable=False))
    op.add_column('fsa_dependent_care_plan', sa.Column('min_contribution', sa.Numeric(precision=9, scale=2), nullable=False))
    op.add_column('hra_plan', sa.Column('min_contribution', sa.Numeric(precision=9, scale=2), nullable=False))
    op.add_column('hsa_plan', sa.Column('min_contribution', sa.Numeric(precision=9, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hsa_plan', 'min_contribution')
    op.drop_column('hra_plan', 'min_contribution')
    op.drop_column('fsa_dependent_care_plan', 'min_contribution')
    op.drop_column('employee_401k_plan', 'min_contribution')
    op.drop_column('employee_401k_plan', 'employer_percent_matched')
    op.drop_column('employee_401k_plan', 'employer_max_contribution')
    ### end Alembic commands ###
