"""add amount to election

Revision ID: 3250d04edb53
Revises: bcc8367757c5
Create Date: 2017-04-25 20:03:23.982769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3250d04edb53'
down_revision = 'bcc8367757c5'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'amount')
    ### end Alembic commands ###
