"""add election period

Revision ID: 341797de2dd7
Revises: 3250d04edb53
Create Date: 2017-04-26 18:59:29.449381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341797de2dd7'
down_revision = '3250d04edb53'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'enrollment', sa.Column('enrollment_period_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrollment', 'enrollment_period', ['enrollment_period_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.drop_column(u'enrollment', 'enrollment_period_id')
    op.drop_table('enrollment_period')
    ### end Alembic commands ###
