"""remove firstname lastname from user

Revision ID: 4acfb73f47b7
Revises: da11423c193e
Create Date: 2016-12-13 21:27:44.761056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acfb73f47b7'
down_revision = 'da11423c193e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    ### end Alembic commands ###
