"""Adding configuration model

Revision ID: 51834463f859
Revises: cb692d28cc2e
Create Date: 2018-01-07 18:06:36.157516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51834463f859'
down_revision = 'cb692d28cc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=155), nullable=True),
    sa.Column('company_text', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
