"""default_ptp_vals_to_0

Revision ID: 55c6d2b4cb56
Revises: 341797de2dd7
Create Date: 2017-04-28 15:32:03.860687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c6d2b4cb56'
down_revision = '341797de2dd7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
