"""add required plan

Revision ID: 671426c000fb
Revises: d80214bee0d7
Create Date: 2017-09-13 21:44:14.499370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671426c000fb'
down_revision = 'd80214bee0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('required_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan', 'plan', ['required_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'required_plan_id')
    # ### end Alembic commands ###
