"""add plan dependents

Revision ID: 6f3ea3429c0b
Revises: 37d11acd5305
Create Date: 2017-12-26 20:08:04.539209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3ea3429c0b'
down_revision = '37d11acd5305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_dependents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('dependent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_id'], [u'dependent.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], [u'plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_dependents')
    # ### end Alembic commands ###
