"""add plan to election

Revision ID: 7c6631d40a75
Revises: 6ba8df84bf54
Create Date: 2016-12-27 13:34:24.248233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6631d40a75'
down_revision = '6ba8df84bf54'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'election', 'plan', ['plan_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.drop_column('election', 'plan_id')
    ### end Alembic commands ###
