"""open enroll start end

Revision ID: 8674f91f80d5
Revises: c0fcbdc6e7a6
Create Date: 2017-10-10 21:24:25.016374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8674f91f80d5'
down_revision = 'c0fcbdc6e7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_period', sa.Column('open_enroll_end', sa.Date(), nullable=False))
    op.add_column('enrollment_period', sa.Column('open_enroll_start', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_period', 'open_enroll_start')
    op.drop_column('enrollment_period', 'open_enroll_end')
    # ### end Alembic commands ###
