"""add active flag to plan

Revision ID: 889e63309fa7
Revises: f4be95baf1af
Create Date: 2017-01-20 22:03:56.086466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889e63309fa7'
down_revision = 'f4be95baf1af'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'is_active')
    ### end Alembic commands ###
