"""address for dependents

Revision ID: 9028cde46ac6
Revises: 4acfb73f47b7
Create Date: 2016-12-13 22:45:03.982030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9028cde46ac6'
down_revision = '4acfb73f47b7'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
