"""add other plan

Revision ID: a0c510d85e9f
Revises: e18c993d93c6
Create Date: 2017-09-13 17:04:25.407973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c510d85e9f'
down_revision = 'e18c993d93c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'plan', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column(u'plan', 'name',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'plan', 'name',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)
    op.alter_column(u'plan', 'description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_table('other_plan')
    # ### end Alembic commands ###
