"""remove min contrib from hra

Revision ID: a9cba09d2611
Revises: 7511f3d20327
Create Date: 2017-08-16 17:35:26.462017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cba09d2611'
down_revision = '7511f3d20327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hra_plan', 'min_contribution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hra_plan', sa.Column('min_contribution', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
