"""add premium matrix to plan

Revision ID: afe102125ec5
Revises: 6a7c63d1428b
Create Date: 2017-09-11 16:01:33.318597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe102125ec5'
down_revision = '6a7c63d1428b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('premium_matrix', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'premium_matrix')
    # ### end Alembic commands ###
