"""increase size of benefit

Revision ID: b30cccc54af6
Revises: 55c6d2b4cb56
Create Date: 2017-04-28 16:52:52.590284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30cccc54af6'
down_revision = '55c6d2b4cb56'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('election', 'amount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=11, scale=2),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('election', 'amount',
               existing_type=sa.Numeric(precision=11, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    ### end Alembic commands ###
