"""add description and special instructions

Revision ID: bcc8367757c5
Revises: 0ab5c7eda52f
Create Date: 2017-04-18 20:13:50.637605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc8367757c5'
down_revision = '0ab5c7eda52f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('plan', sa.Column('special_instructions', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'special_instructions')
    op.drop_column('plan', 'description')
    ### end Alembic commands ###
