"""initial migration

Revision ID: da11423c193e
Revises:
Create Date: 2016-12-11 23:04:08.957719

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from perks import models


# revision identifiers, used by Alembic.
revision = 'da11423c193e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_1', sa.Unicode(length=100), nullable=False),
    sa.Column('street_2', sa.Unicode(length=100), nullable=True),
    sa.Column('city', sa.Unicode(length=100), nullable=False),
    sa.Column('state', sqlalchemy_utils.types.choice.ChoiceType(models.SMOKER_TYPES), nullable=True),
    sa.Column('zip_code', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('api_endpoint', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependent_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domestic_partner_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_time_only', sa.Boolean(), nullable=True),
    sa.Column('minimum_days_employed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=True),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantype', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.Unicode(length=20), nullable=True),
    sa.Column('public_name', sa.Unicode(length=30), nullable=True),
    sa.Column('cust_service_phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('not_available_in', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('pricing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PRICING_TYPES), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('label', sa.Unicode(length=255), server_default=u'', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('last_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('age_banded_premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cancer_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cricial_illness_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dental_plan',
    sa.Column('group_number', sa.Unicode(length=24), nullable=False),
    sa.Column('original_effective_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('existing', sa.Boolean(), nullable=False),
    sa.Column('list_billed', sa.Boolean(), nullable=True),
    sa.Column('doctor_selection_required', sa.Boolean(), nullable=True),
    sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True),
    sa.Column('cobra_eligible', sa.Boolean(), nullable=False),
    sa.Column('pre_tax', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('bundled_with_medical', sa.Boolean(), nullable=False),
    sa.Column('bundled_with_vision', sa.Boolean(), nullable=False),
    sa.Column('bundled_with_id', sa.Integer(), nullable=True),
    sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True),
    sa.ForeignKeyConstraint(['bundled_with_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eap_plan',
    sa.Column('minimum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('middle_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('last_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('ssn', sa.Unicode(length=11), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(models.GENDER_TYPES), nullable=True),
    sa.Column('marital_status', sqlalchemy_utils.types.choice.ChoiceType(models.MARITAL_STATUSES), nullable=True),
    sa.Column('smoker_type', sqlalchemy_utils.types.choice.ChoiceType(models.SMOKER_TYPES), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('employee_number', sa.Unicode(length=25), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('sub_group_id', sa.String(length=50), nullable=False),
    sa.Column('sub_group_effective_date', sa.Date(), nullable=False),
    sa.Column('salary_mode', sqlalchemy_utils.types.choice.ChoiceType(models.SALARY_MODE_TYPES), nullable=True),
    sa.Column('salary_effective_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('alternate_phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('emergency_contact_phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_401k_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fsa_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hsa_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_add_dependent_plan',
    sa.Column('minimum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_add_plan',
    sa.Column('minimum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('long_term_care_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ltd_plan',
    sa.Column('minimum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_plan',
    sa.Column('group_number', sa.Unicode(length=24), nullable=False),
    sa.Column('original_effective_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('existing', sa.Boolean(), nullable=False),
    sa.Column('list_billed', sa.Boolean(), nullable=True),
    sa.Column('doctor_selection_required', sa.Boolean(), nullable=True),
    sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True),
    sa.Column('cobra_eligible', sa.Boolean(), nullable=False),
    sa.Column('pre_tax', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('self_funded', sa.Boolean(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_transit_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_tier_premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('tier_type', sqlalchemy_utils.types.choice.ChoiceType(models.TIER_TYPES), nullable=True),
    sa.Column('premium', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('employer_portion', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('employee_portion', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('std_plan',
    sa.Column('minimum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_interval', sqlalchemy_utils.types.choice.ChoiceType(models.PAYOUT_INTERVAL_TYPES), nullable=True),
    sa.Column('max_weekly_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_monthly_benefit', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('benefit_percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('mandatory_in_states', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_plan',
    sa.Column('group_number', sa.Unicode(length=24), nullable=False),
    sa.Column('original_effective_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('existing', sa.Boolean(), nullable=False),
    sa.Column('list_billed', sa.Boolean(), nullable=True),
    sa.Column('doctor_selection_required', sa.Boolean(), nullable=True),
    sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True),
    sa.Column('cobra_eligible', sa.Boolean(), nullable=False),
    sa.Column('pre_tax', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('bundled_with_medical', sa.Boolean(), nullable=False),
    sa.Column('bundled_with_dental', sa.Boolean(), nullable=False),
    sa.Column('bundled_with_id', sa.Integer(), nullable=True),
    sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True),
    sa.ForeignKeyConstraint(['bundled_with_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('middle_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('last_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('ssn', sa.Unicode(length=11), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(models.GENDER_TYPES), nullable=True),
    sa.Column('marital_status', sqlalchemy_utils.types.choice.ChoiceType(models.MARITAL_STATUSES), nullable=True),
    sa.Column('smoker_type', sqlalchemy_utils.types.choice.ChoiceType(models.SMOKER_TYPES), nullable=True),
    sa.Column('beneficiary_type', sqlalchemy_utils.types.choice.ChoiceType(models.BENEFICIARY_TYPES), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('middle_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('last_name', sa.Unicode(length=50), server_default=u'', nullable=False),
    sa.Column('ssn', sa.Unicode(length=11), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(models.GENDER_TYPES), nullable=True),
    sa.Column('marital_status', sqlalchemy_utils.types.choice.ChoiceType(models.MARITAL_STATUSES), nullable=True),
    sa.Column('smoker_type', sqlalchemy_utils.types.choice.ChoiceType(models.SMOKER_TYPES), nullable=True),
    sa.Column('dependent_type', sqlalchemy_utils.types.choice.ChoiceType(models.DEPENDENT_TYPES), nullable=True),
    sa.Column('full_time_student', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('disability_date', sa.Date(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('life_event', sqlalchemy_utils.types.choice.ChoiceType(models.LIFE_EVENT_TYPES), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('plan_tier_premium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['plan_tier_premium_id'], ['plan_tier_premium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_choice')
    op.drop_table('enrollment')
    op.drop_table('dependent')
    op.drop_table('beneficiary')
    op.drop_table('vision_plan')
    op.drop_table('user_roles')
    op.drop_table('std_plan')
    op.drop_table('plan_tier_premium')
    op.drop_table('parking_transit_plan')
    op.drop_table('other_plan')
    op.drop_table('medical_plan')
    op.drop_table('ltd_plan')
    op.drop_table('long_term_care_plan')
    op.drop_table('life_add_plan')
    op.drop_table('life_add_dependent_plan')
    op.drop_table('hsa_plan')
    op.drop_table('fsa_plan')
    op.drop_table('employee_401k_plan')
    op.drop_table('employee')
    op.drop_table('eap_plan')
    op.drop_table('dental_plan')
    op.drop_table('cricial_illness_plan')
    op.drop_table('cancer_plan')
    op.drop_table('age_banded_premium')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('plan')
    op.drop_table('location')
    op.drop_table('employee_eligibility')
    op.drop_table('domestic_partner_eligibility')
    op.drop_table('dependent_eligibility')
    op.drop_table('carrier')
    op.drop_table('address')
    ### end Alembic commands ###
