"""add coverage amount

Revision ID: e0303daafe40
Revises: ac7fbb7cd682
Create Date: 2017-08-07 10:44:03.556850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0303daafe40'
down_revision = 'ac7fbb7cd682'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('coverage_amount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'coverage_amount')
    ### end Alembic commands ###
