"""group_number

Revision ID: edfff3cb14d4
Revises: 7cab846b56be
Create Date: 2017-04-11 21:25:56.758729

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from perks import models


# revision identifiers, used by Alembic.
revision = 'edfff3cb14d4'
down_revision = '7cab846b56be'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dental_vision_bundle_plan', sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('carrier_id', sa.Integer(), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('cobra_eligible', sa.Boolean(), nullable=False))
    op.add_column('dental_vision_bundle_plan', sa.Column('doctor_selection_required', sa.Boolean(), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('existing', sa.Boolean(), nullable=False))
    op.add_column('dental_vision_bundle_plan', sa.Column('group_number', sa.Unicode(length=24), nullable=False))
    op.add_column('dental_vision_bundle_plan', sa.Column('list_billed', sa.Boolean(), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('original_effective_date', sa.Date(), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True))
    op.add_column('dental_vision_bundle_plan', sa.Column('pre_tax', sa.Boolean(), nullable=False))
    op.add_column('dental_vision_bundle_plan', sa.Column('renewal_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'dental_vision_bundle_plan', 'carrier', ['carrier_id'], ['id'])
    op.add_column('medical_dental_bundle_plan', sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('carrier_id', sa.Integer(), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('cobra_eligible', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_bundle_plan', sa.Column('doctor_selection_required', sa.Boolean(), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('existing', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_bundle_plan', sa.Column('group_number', sa.Unicode(length=24), nullable=False))
    op.add_column('medical_dental_bundle_plan', sa.Column('list_billed', sa.Boolean(), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('original_effective_date', sa.Date(), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('pre_tax', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_bundle_plan', sa.Column('renewal_date', sa.Date(), nullable=True))
    op.add_column('medical_dental_bundle_plan', sa.Column('self_funded', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'medical_dental_bundle_plan', 'carrier', ['carrier_id'], ['id'])
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('carrier_id', sa.Integer(), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('cobra_eligible', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('doctor_selection_required', sa.Boolean(), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('existing', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('group_number', sa.Unicode(length=24), nullable=False))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('list_billed', sa.Boolean(), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('original_effective_date', sa.Date(), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('pre_tax', sa.Boolean(), nullable=False))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('renewal_date', sa.Date(), nullable=True))
    op.add_column('medical_dental_vision_bundle_plan', sa.Column('self_funded', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'medical_dental_vision_bundle_plan', 'carrier', ['carrier_id'], ['id'])
    op.add_column('medical_vision_bundle_plan', sa.Column('account_rep_name', sa.Unicode(length=40), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('carrier_id', sa.Integer(), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('cobra_eligible', sa.Boolean(), nullable=False))
    op.add_column('medical_vision_bundle_plan', sa.Column('doctor_selection_required', sa.Boolean(), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('existing', sa.Boolean(), nullable=False))
    op.add_column('medical_vision_bundle_plan', sa.Column('group_number', sa.Unicode(length=24), nullable=False))
    op.add_column('medical_vision_bundle_plan', sa.Column('list_billed', sa.Boolean(), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('original_effective_date', sa.Date(), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('plan_termination_timing_type_id', sqlalchemy_utils.types.choice.ChoiceType(models.PLAN_TERMINATION_TIMING_TYPES), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('pre_tax', sa.Boolean(), nullable=False))
    op.add_column('medical_vision_bundle_plan', sa.Column('renewal_date', sa.Date(), nullable=True))
    op.add_column('medical_vision_bundle_plan', sa.Column('self_funded', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'medical_vision_bundle_plan', 'carrier', ['carrier_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_vision_bundle_plan', type_='foreignkey')
    op.drop_column('medical_vision_bundle_plan', 'self_funded')
    op.drop_column('medical_vision_bundle_plan', 'renewal_date')
    op.drop_column('medical_vision_bundle_plan', 'pre_tax')
    op.drop_column('medical_vision_bundle_plan', 'plan_termination_timing_type_id')
    op.drop_column('medical_vision_bundle_plan', 'original_effective_date')
    op.drop_column('medical_vision_bundle_plan', 'list_billed')
    op.drop_column('medical_vision_bundle_plan', 'group_number')
    op.drop_column('medical_vision_bundle_plan', 'existing')
    op.drop_column('medical_vision_bundle_plan', 'doctor_selection_required')
    op.drop_column('medical_vision_bundle_plan', 'cobra_eligible')
    op.drop_column('medical_vision_bundle_plan', 'carrier_id')
    op.drop_column('medical_vision_bundle_plan', 'account_rep_name')
    op.drop_constraint(None, 'medical_dental_vision_bundle_plan', type_='foreignkey')
    op.drop_column('medical_dental_vision_bundle_plan', 'self_funded')
    op.drop_column('medical_dental_vision_bundle_plan', 'renewal_date')
    op.drop_column('medical_dental_vision_bundle_plan', 'pre_tax')
    op.drop_column('medical_dental_vision_bundle_plan', 'plan_termination_timing_type_id')
    op.drop_column('medical_dental_vision_bundle_plan', 'original_effective_date')
    op.drop_column('medical_dental_vision_bundle_plan', 'list_billed')
    op.drop_column('medical_dental_vision_bundle_plan', 'group_number')
    op.drop_column('medical_dental_vision_bundle_plan', 'existing')
    op.drop_column('medical_dental_vision_bundle_plan', 'doctor_selection_required')
    op.drop_column('medical_dental_vision_bundle_plan', 'cobra_eligible')
    op.drop_column('medical_dental_vision_bundle_plan', 'carrier_id')
    op.drop_column('medical_dental_vision_bundle_plan', 'account_rep_name')
    op.drop_constraint(None, 'medical_dental_bundle_plan', type_='foreignkey')
    op.drop_column('medical_dental_bundle_plan', 'self_funded')
    op.drop_column('medical_dental_bundle_plan', 'renewal_date')
    op.drop_column('medical_dental_bundle_plan', 'pre_tax')
    op.drop_column('medical_dental_bundle_plan', 'plan_termination_timing_type_id')
    op.drop_column('medical_dental_bundle_plan', 'original_effective_date')
    op.drop_column('medical_dental_bundle_plan', 'list_billed')
    op.drop_column('medical_dental_bundle_plan', 'group_number')
    op.drop_column('medical_dental_bundle_plan', 'existing')
    op.drop_column('medical_dental_bundle_plan', 'doctor_selection_required')
    op.drop_column('medical_dental_bundle_plan', 'cobra_eligible')
    op.drop_column('medical_dental_bundle_plan', 'carrier_id')
    op.drop_column('medical_dental_bundle_plan', 'account_rep_name')
    op.drop_constraint(None, 'dental_vision_bundle_plan', type_='foreignkey')
    op.drop_column('dental_vision_bundle_plan', 'renewal_date')
    op.drop_column('dental_vision_bundle_plan', 'pre_tax')
    op.drop_column('dental_vision_bundle_plan', 'plan_termination_timing_type_id')
    op.drop_column('dental_vision_bundle_plan', 'original_effective_date')
    op.drop_column('dental_vision_bundle_plan', 'list_billed')
    op.drop_column('dental_vision_bundle_plan', 'group_number')
    op.drop_column('dental_vision_bundle_plan', 'existing')
    op.drop_column('dental_vision_bundle_plan', 'doctor_selection_required')
    op.drop_column('dental_vision_bundle_plan', 'cobra_eligible')
    op.drop_column('dental_vision_bundle_plan', 'carrier_id')
    op.drop_column('dental_vision_bundle_plan', 'account_rep_name')
    ### end Alembic commands ###
